spring.application.name=1_data_source

# data source definition
spring.datasource.url=jdbc:mysql://localhost:3306/purchase
spring.datasource.username=${mysql-user}
spring.datasource.password=${mysql-pass}

# instruct spring to use the schema.sql file & create the necessary tables.
spring.sql.init.mode=always