spring.application.name=1_transactions

# data source configuration
spring.datasource.url=jdbc:mysql://localhost:3306/accounts
spring.datasource.username=${env.MYSQL-USER}
spring.datasource.password=${env.MYSQL-PASS}
spring.sql.init.mode=always